### ISSUE TITLE
Enhance Architecture Description with Informal Diagrams

### ISSUE THREAD

**Issue by VladoSruk** [software-engineering-group-3/crisis-guard#16]
The architecture description would benefit from adding informal diagrams that visually illustrate key components, subsystems, and data flows. Informal diagrams would make the architecture more accessible, providing team members and stakeholders with a clearer understanding of the system at a glance.
Requirements:
1.	Add Overview Diagrams: Include high-level informal diagrams to depict:
o	Core components and their interactions (e.g., client, server, database, third-party services).
o	Main subsystems such as Authentication, User Management, Gym Management, and Recommendation Service.
o	Data flow and major connections between components to showcase how information travels through the system.
2.	Review and Validate: Ensure the diagrams accurately reflect the architecture 
3.	 In second iterration you will provide more detailed diagrams
Acceptance Criteria:
1.	Clarity and Accuracy: Diagrams should clearly depict key architectural components, data flows, and connections, with accurate labels.
2.	Consistency with Existing Documentation: Diagrams should align with the architectural structure described in text, providing visual reinforcement.
3.	Simplification: Use informal notation to present concepts in a way that is easy for any team member or stakeholder to follow.
4.	Regularly update these diagrams to reflect any architectural changes or improvements made during the project’s lifecycle.

Reasons for Implementation:
1.	Improves Comprehension: Diagrams provide a quick and intuitive overview, enhancing the readability of complex architectural concepts.
2.	Supports Collaboration: Visual aids make it easier for team members to discuss architecture, design improvements, and future modifications.
3.	Enhances Documentation Quality: A visually enriched description will make the documentation more complete and professional, especially for new contributors and stakeholders.

**Comment by BorisMilicevic1** [comment]
Informal diagrams are posted on wiki.
